# Generated by Django 6.0.3 on 2026-04-24 13:25

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Report',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('location', models.CharField(max_length=100)),
                ('status', models.CharField(choices=[('REPORTED', 'REPORTED'), ('VERIFIED', 'VERIFIED'), ('IN_PROGRESS', 'IN_PROGRESS'), ('RESOLVED', 'RESOLVED')], max_length=20)),
            ],
        ),
    ]
